package rikka.shizuku.manager;

/**
 * Previously generated by dev.rikka.tools.autoresconfig at build time.
 * That plugin only supports application modules, so for the manager to build
 * as a library this list is now a static source file.
 * Regenerate manually when new values-* resource folders are added.
 */
public final class ShizukuLocales {

    public static final String[] LOCALES = {
            "SYSTEM",
            "af", "ar", "az", "cs", "de", "el", "es", "fa", "fi", "fil",
            "fr", "hu", "hy", "id", "it", "ja", "ka", "ko", "ms", "nl",
            "no", "pl", "pt", "pt-BR", "ro", "ru", "sl", "sr", "sv",
            "ta", "th", "tr", "uk", "vi", "zh-CN", "zh-TW"
    };

    public static final String[] DISPLAY_LOCALES = {
            "SYSTEM",
            "af", "ar", "az", "cs", "de", "el", "es", "fa", "fi", "fil",
            "fr", "hu", "hy", "id", "it", "ja", "ka", "ko", "ms", "nl",
            "no", "pl", "pt", "pt-BR", "ro", "ru", "sl", "sr", "sv",
            "ta", "th", "tr", "uk", "vi", "zh-CN", "zh-TW"
    };

    private ShizukuLocales() {
    }
}
